### ISSUE TITLE
Missing Yolol chips!

### ISSUE THREAD

**Issue by Bluelight82** [Thaccus/Starbase-Nav-Suite#5]
Why is there a turret and no Yolol chips in the example file NavSuite Adv7?

**Comment by Thaccus** [comment]
I just downloaded NavSuite_Adv7.fbe from the main page here and I see all the parts. Can you show me what you see?
![image](https://user-images.githubusercontent.com/7218906/178737872-4c04c6a8-b6d3-4551-98e9-1dc49ee1bf49.png)

**Comment by Bluelight82** [comment]
Sorry my mistake! will cancel issue!
